version: "3.8"

networks:
  my_custom_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.31.188.0/26
        # - gateway: 172.31.188.1

services:
  nginx:
    image: nginx:latest
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "2"
    networks:
      - my_custom_network
    ports:
      - 80:80
      - 8080:80
      - 443:443
