version: "3.8"

networks:
  net:
    name: my_custom_network:
    external: true  

services:
  nginx:
    image: nginx:latest
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "2"
    networks:
      - net
    ports:
      - 80:80
      - 8080:80
      - 443:443
