version: "3"

services:
  ftp:
    image: nginx
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "2"
    ports:
      - 80:80
      - 8080:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
      - html:/usr/share/nginx/html:ro

volumes:
  html:
