version: "3"

services:
  ftp:
    image: my-nginx:latest
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "2"
    deploy:
      replicas: 1
    ports:
      - 80:80
      - 8080:80
      - 443:443
